# Generated by Django 5.2.8 on 2025-11-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkateApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
